id: P000521
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:44:18.842942
source_metadata:
  id: bdr:W20828
  title: གནས་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    002af2a033704556ba646b929f6b6bf8:
      image_group_id: I4244
      title: ''
      volume_number: 1
      total_pages: 630
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
