id: P000521
initial_creation_type: ocr
source_metadata:
  id: bdr:W20828
  title: གནས་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    002af2a033704556ba646b929f6b6bf8:
      image_group_id: I4244
      title: ''
      volume_number: 1
      total_pages: 630
      base_file: v001.txt
ebook_metadata:
  title: གནས་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  sku: P000521
  cover: cover.jpg
  layers:
  - pagination
